/* Generated by tools/sync_assets.py — do not edit.
 * Source: data/verses/en.json
 */
.pragma library

var DATA = {
  "language": "en",
  "translation": {
    "name": "World English Bible",
    "shortName": "WEB",
    "year": 2000,
    "license": "public-domain",
    "sourceUrl": "https://github.com/midvash/bible-data"
  },
  "count": 438,
  "verses": [
    {
      "id": "1.1.1",
      "ref": "Genesis 1:1",
      "text": "In the beginning, God created the heavens and the earth."
    },
    {
      "id": "1.1.27",
      "ref": "Genesis 1:27",
      "text": "God created man in his own image. In God’s image he created him; male and female he created them."
    },
    {
      "id": "1.9.13",
      "ref": "Genesis 9:13",
      "text": "I set my rainbow in the cloud, and it will be a sign of a covenant between me and the earth."
    },
    {
      "id": "1.28.15",
      "ref": "Genesis 28:15",
      "text": "Behold, I am with you, and will keep you, wherever you go, and will bring you again into this land. For I will not leave you until I have done that which I have spoken of to you.”"
    },
    {
      "id": "1.50.20",
      "ref": "Genesis 50:20",
      "text": "As for you, you meant evil against me, but God meant it for good, to save many people alive, as is happening today."
    },
    {
      "id": "2.14.14",
      "ref": "Exodus 14:14",
      "text": "The LORD will fight for you, and you shall be still.”"
    },
    {
      "id": "2.15.2",
      "ref": "Exodus 15:2",
      "text": "The LORD is my strength and song. He has become my salvation. This is my God, and I will praise him; my father’s God, and I will exalt him."
    },
    {
      "id": "2.20.12",
      "ref": "Exodus 20:12",
      "text": "“Honor your father and your mother, that your days may be long in the land which the LORD your God gives you."
    },
    {
      "id": "2.33.14",
      "ref": "Exodus 33:14",
      "text": "He said, “My presence will go with you, and I will give you rest.”"
    },
    {
      "id": "2.34.6",
      "ref": "Exodus 34:6",
      "text": "The LORD passed by before him, and proclaimed, “The LORD! The LORD, a merciful and gracious God, slow to anger, and abundant in loving kindness and truth,"
    },
    {
      "id": "3.19.18",
      "ref": "Leviticus 19:18",
      "text": "“‘You shall not take vengeance, nor bear any grudge against the children of your people; but you shall love your neighbor as yourself. I am the LORD."
    },
    {
      "id": "4.6.24-26",
      "ref": "Numbers 6:24-26",
      "text": "‘The LORD bless you, and keep you. The LORD make his face to shine on you, and be gracious to you. The LORD lift up his face toward you, and give you peace.’"
    },
    {
      "id": "4.23.19",
      "ref": "Numbers 23:19",
      "text": "God is not a man, that he should lie, nor a son of man, that he should repent. Has he said, and he won’t do it? Or has he spoken, and he won’t make it good?"
    },
    {
      "id": "5.4.29",
      "ref": "Deuteronomy 4:29",
      "text": "But from there you shall seek the LORD your God, and you will find him when you search after him with all your heart and with all your soul."
    },
    {
      "id": "5.6.5",
      "ref": "Deuteronomy 6:5",
      "text": "You shall love the LORD your God with all your heart, with all your soul, and with all your might."
    },
    {
      "id": "5.7.9",
      "ref": "Deuteronomy 7:9",
      "text": "Know therefore that the LORD your God himself is God, the faithful God, who keeps covenant and loving kindness to a thousand generations with those who love him and keep his commandments,"
    },
    {
      "id": "5.30.19",
      "ref": "Deuteronomy 30:19",
      "text": "I call heaven and earth to witness against you today that I have set before you life and death, the blessing and the curse. Therefore choose life, that you may live, you and your descendants,"
    },
    {
      "id": "5.31.6",
      "ref": "Deuteronomy 31:6",
      "text": "Be strong and courageous. Don’t be afraid or scared of them, for the LORD your God himself is who goes with you. He will not fail you nor forsake you.”"
    },
    {
      "id": "5.31.8",
      "ref": "Deuteronomy 31:8",
      "text": "The LORD himself is who goes before you. He will be with you. He will not fail you nor forsake you. Don’t be afraid. Don’t be discouraged.”"
    },
    {
      "id": "5.33.27",
      "ref": "Deuteronomy 33:27",
      "text": "The eternal God is your dwelling place. Underneath are the everlasting arms. He thrust out the enemy from before you, and said, ‘Destroy!’"
    },
    {
      "id": "6.1.5",
      "ref": "Joshua 1:5",
      "text": "No man will be able to stand before you all the days of your life. As I was with Moses, so I will be with you. I will not fail you nor forsake you."
    },
    {
      "id": "6.1.8",
      "ref": "Joshua 1:8",
      "text": "This book of the law shall not depart from your mouth, but you shall meditate on it day and night, that you may observe to do according to all that is written in it; for then you shall make your way prosperous, and then you shall have good success."
    },
    {
      "id": "6.1.9",
      "ref": "Joshua 1:9",
      "text": "Haven’t I commanded you? Be strong and courageous. Don’t be afraid. Don’t be dismayed, for the LORD your God is with you wherever you go.”"
    },
    {
      "id": "6.24.15",
      "ref": "Joshua 24:15",
      "text": "If it seems evil to you to serve the LORD, choose today whom you will serve; whether the gods which your fathers served that were beyond the River, or the gods of the Amorites, in whose land you dwell; but as for me and my house, we will serve the LORD.”"
    },
    {
      "id": "7.6.12",
      "ref": "Judges 6:12",
      "text": "The LORD’s angel appeared to him, and said to him, “The LORD is with you, you mighty man of valor!”"
    },
    {
      "id": "8.1.16",
      "ref": "Ruth 1:16",
      "text": "Ruth said, “Don’t urge me to leave you, and to return from following you, for where you go, I will go; and where you stay, I will stay. Your people will be my people, and your God my God."
    },
    {
      "id": "9.12.24",
      "ref": "1 Samuel 12:24",
      "text": "Only fear the LORD, and serve him in truth with all your heart; for consider what great things he has done for you."
    },
    {
      "id": "9.16.7",
      "ref": "1 Samuel 16:7",
      "text": "But the LORD said to Samuel, “Don’t look on his face, or on the height of his stature, because I have rejected him; for I don’t see as man sees. For man looks at the outward appearance, but the LORD looks at the heart.”"
    },
    {
      "id": "10.22.2-3",
      "ref": "2 Samuel 22:2-3",
      "text": "and he said: “The LORD is my rock, my fortress, and my deliverer, even mine; God is my rock in whom I take refuge; my shield, and the horn of my salvation, my high tower, and my refuge. My savior, you save me from violence."
    },
    {
      "id": "10.22.31",
      "ref": "2 Samuel 22:31",
      "text": "As for God, his way is perfect. The LORD’s word is tested. He is a shield to all those who take refuge in him."
    },
    {
      "id": "11.8.23",
      "ref": "1 Kings 8:23",
      "text": "and he said, “LORD, the God of Israel, there is no God like you, in heaven above, or on earth beneath; who keeps covenant and loving kindness with your servants who walk before you with all their heart;"
    },
    {
      "id": "12.6.16",
      "ref": "2 Kings 6:16",
      "text": "He answered, “Don’t be afraid, for those who are with us are more than those who are with them.”"
    },
    {
      "id": "13.16.11",
      "ref": "1 Chronicles 16:11",
      "text": "Seek the LORD and his strength. Seek his face forever more."
    },
    {
      "id": "13.16.34",
      "ref": "1 Chronicles 16:34",
      "text": "Oh give thanks to the LORD, for he is good, for his loving kindness endures forever."
    },
    {
      "id": "13.28.20",
      "ref": "1 Chronicles 28:20",
      "text": "David said to Solomon his son, “Be strong and courageous, and do it. Don’t be afraid, nor be dismayed, for the LORD God, even my God, is with you. He will not fail you nor forsake you, until all the work for the service of the LORD’s house is finished."
    },
    {
      "id": "13.29.11",
      "ref": "1 Chronicles 29:11",
      "text": "Yours, LORD, is the greatness, the power, the glory, the victory, and the majesty! For all that is in the heavens and in the earth is yours. Yours is the kingdom, LORD, and you are exalted as head above all."
    },
    {
      "id": "14.7.14",
      "ref": "2 Chronicles 7:14",
      "text": "if my people who are called by my name will humble themselves, pray, seek my face, and turn from their wicked ways, then I will hear from heaven, will forgive their sin, and will heal their land."
    },
    {
      "id": "14.15.7",
      "ref": "2 Chronicles 15:7",
      "text": "But you be strong! Don’t let your hands be slack, for your work will be rewarded.”"
    },
    {
      "id": "14.16.9",
      "ref": "2 Chronicles 16:9",
      "text": "For the LORD’s eyes run back and forth throughout the whole earth, to show himself strong in the behalf of them whose heart is perfect toward him. You have done foolishly in this; for from now on you will have wars.”"
    },
    {
      "id": "14.20.15",
      "ref": "2 Chronicles 20:15",
      "text": "and he said, “Listen, all Judah, and you inhabitants of Jerusalem, and you, King Jehoshaphat. The LORD says to you, ‘Don’t be afraid, and don’t be dismayed because of this great multitude; for the battle is not yours, but God’s."
    },
    {
      "id": "15.8.22",
      "ref": "Ezra 8:22",
      "text": "For I was ashamed to ask of the king a band of soldiers and horsemen to help us against the enemy on the way, because we had spoken to the king, saying, “The hand of our God is on all those who seek him, for good; but his power and his wrath is against all those who forsake him.”"
    },
    {
      "id": "16.8.10",
      "ref": "Nehemiah 8:10",
      "text": "Then he said to them, “Go your way. Eat the fat, drink the sweet, and send portions to him for whom nothing is prepared, for today is holy to our Lord. Don’t be grieved, for the joy of the LORD is your strength.”"
    },
    {
      "id": "16.9.6",
      "ref": "Nehemiah 9:6",
      "text": "You are the LORD, even you alone. You have made heaven, the heaven of heavens, with all their army, the earth and all things that are on it, the seas and all that is in them, and you preserve them all. The army of heaven worships you."
    },
    {
      "id": "17.4.14",
      "ref": "Esther 4:14",
      "text": "For if you remain silent now, then relief and deliverance will come to the Jews from another place, but you and your father’s house will perish. Who knows if you haven’t come to the kingdom for such a time as this?”"
    },
    {
      "id": "18.19.25",
      "ref": "Job 19:25",
      "text": "But as for me, I know that my Redeemer lives. In the end, he will stand upon the earth."
    },
    {
      "id": "18.23.10",
      "ref": "Job 23:10",
      "text": "But he knows the way that I take. When he has tried me, I will come out like gold."
    },
    {
      "id": "18.42.2",
      "ref": "Job 42:2",
      "text": "“I know that you can do all things, and that no purpose of yours can be restrained."
    },
    {
      "id": "19.1.1-2",
      "ref": "Psalms 1:1-2",
      "text": "Blessed is the man who doesn’t walk in the counsel of the wicked, nor stand on the path of sinners, nor sit in the seat of scoffers; but his delight is in the LORD’s law. On his law he meditates day and night."
    },
    {
      "id": "19.4.8",
      "ref": "Psalms 4:8",
      "text": "In peace I will both lay myself down and sleep, for you alone, LORD, make me live in safety."
    },
    {
      "id": "19.5.3",
      "ref": "Psalms 5:3",
      "text": "LORD, in the morning you will hear my voice. In the morning I will lay my requests before you, and will watch expectantly."
    },
    {
      "id": "19.8.3-4",
      "ref": "Psalms 8:3-4",
      "text": "When I consider your heavens, the work of your fingers, the moon and the stars, which you have ordained, what is man, that you think of him? What is the son of man, that you care for him?"
    },
    {
      "id": "19.9.9",
      "ref": "Psalms 9:9",
      "text": "The LORD will also be a high tower for the oppressed; a high tower in times of trouble."
    },
    {
      "id": "19.16.8",
      "ref": "Psalms 16:8",
      "text": "I have set the LORD always before me. Because he is at my right hand, I shall not be moved."
    },
    {
      "id": "19.16.11",
      "ref": "Psalms 16:11",
      "text": "You will show me the path of life. In your presence is fullness of joy. In your right hand there are pleasures forever more."
    },
    {
      "id": "19.18.2",
      "ref": "Psalms 18:2",
      "text": "The LORD is my rock, my fortress, and my deliverer; my God, my rock, in whom I take refuge; my shield, and the horn of my salvation, my high tower."
    },
    {
      "id": "19.19.1",
      "ref": "Psalms 19:1",
      "text": "The heavens declare the glory of God. The expanse shows his handiwork."
    },
    {
      "id": "19.19.14",
      "ref": "Psalms 19:14",
      "text": "Let the words of my mouth and the meditation of my heart be acceptable in your sight, LORD, my rock, and my redeemer."
    },
    {
      "id": "19.20.7",
      "ref": "Psalms 20:7",
      "text": "Some trust in chariots, and some in horses, but we trust in the name of the LORD our God."
    },
    {
      "id": "19.23.1",
      "ref": "Psalms 23:1",
      "text": "The LORD is my shepherd; I shall lack nothing."
    },
    {
      "id": "19.23.4",
      "ref": "Psalms 23:4",
      "text": "Even though I walk through the valley of the shadow of death, I will fear no evil, for you are with me. Your rod and your staff, they comfort me."
    },
    {
      "id": "19.23.6",
      "ref": "Psalms 23:6",
      "text": "Surely goodness and loving kindness shall follow me all the days of my life, and I will dwell in the LORD’s house forever."
    },
    {
      "id": "19.25.4-5",
      "ref": "Psalms 25:4-5",
      "text": "Show me your ways, LORD. Teach me your paths. Guide me in your truth, and teach me, for you are the God of my salvation. I wait for you all day long."
    },
    {
      "id": "19.27.1",
      "ref": "Psalms 27:1",
      "text": "The LORD is my light and my salvation. Whom shall I fear? The LORD is the strength of my life. Of whom shall I be afraid?"
    },
    {
      "id": "19.27.14",
      "ref": "Psalms 27:14",
      "text": "Wait for the LORD. Be strong, and let your heart take courage. Yes, wait for the LORD."
    },
    {
      "id": "19.28.7",
      "ref": "Psalms 28:7",
      "text": "The LORD is my strength and my shield. My heart has trusted in him, and I am helped. Therefore my heart greatly rejoices. With my song I will thank him."
    },
    {
      "id": "19.30.5",
      "ref": "Psalms 30:5",
      "text": "For his anger is but for a moment. His favor is for a lifetime. Weeping may stay for the night, but joy comes in the morning."
    },
    {
      "id": "19.31.24",
      "ref": "Psalms 31:24",
      "text": "Be strong, and let your heart take courage, all you who hope in the LORD."
    },
    {
      "id": "19.32.8",
      "ref": "Psalms 32:8",
      "text": "I will instruct you and teach you in the way which you shall go. I will counsel you with my eye on you."
    },
    {
      "id": "19.33.4",
      "ref": "Psalms 33:4",
      "text": "For the LORD’s word is right. All his work is done in faithfulness."
    },
    {
      "id": "19.34.8",
      "ref": "Psalms 34:8",
      "text": "Oh taste and see that the LORD is good. Blessed is the man who takes refuge in him."
    },
    {
      "id": "19.34.18",
      "ref": "Psalms 34:18",
      "text": "The LORD is near to those who have a broken heart, and saves those who have a crushed spirit."
    },
    {
      "id": "19.36.5",
      "ref": "Psalms 36:5",
      "text": "Your loving kindness, LORD, is in the heavens. Your faithfulness reaches to the skies."
    },
    {
      "id": "19.37.4",
      "ref": "Psalms 37:4",
      "text": "Also delight yourself in the LORD, and he will give you the desires of your heart."
    },
    {
      "id": "19.37.5",
      "ref": "Psalms 37:5",
      "text": "Commit your way to the LORD. Trust also in him, and he will do this:"
    },
    {
      "id": "19.37.7",
      "ref": "Psalms 37:7",
      "text": "Rest in the LORD, and wait patiently for him. Don’t fret because of him who prospers in his way, because of the man who makes wicked plots happen."
    },
    {
      "id": "19.40.1",
      "ref": "Psalms 40:1",
      "text": "I waited patiently for the LORD. He turned to me, and heard my cry."
    },
    {
      "id": "19.42.1",
      "ref": "Psalms 42:1",
      "text": "As the deer pants for the water brooks, so my soul pants after you, God."
    },
    {
      "id": "19.42.11",
      "ref": "Psalms 42:11",
      "text": "Why are you in despair, my soul? Why are you disturbed within me? Hope in God! For I shall still praise him, the saving help of my countenance, and my God."
    },
    {
      "id": "19.46.1",
      "ref": "Psalms 46:1",
      "text": "God is our refuge and strength, a very present help in trouble."
    },
    {
      "id": "19.46.10",
      "ref": "Psalms 46:10",
      "text": "“Be still, and know that I am God. I will be exalted among the nations. I will be exalted in the earth.”"
    },
    {
      "id": "19.51.10",
      "ref": "Psalms 51:10",
      "text": "Create in me a clean heart, O God. Renew a right spirit within me."
    },
    {
      "id": "19.55.22",
      "ref": "Psalms 55:22",
      "text": "Cast your burden on the LORD and he will sustain you. He will never allow the righteous to be moved."
    },
    {
      "id": "19.56.3",
      "ref": "Psalms 56:3",
      "text": "When I am afraid, I will put my trust in you."
    },
    {
      "id": "19.62.1-2",
      "ref": "Psalms 62:1-2",
      "text": "To Jeduthun. A Psalm by David. My soul rests in God alone. My salvation is from him. He alone is my rock, my salvation, and my fortress. I will never be greatly shaken."
    },
    {
      "id": "19.63.1",
      "ref": "Psalms 63:1",
      "text": "God, you are my God. I will earnestly seek you. My soul thirsts for you. My flesh longs for you, in a dry and weary land, where there is no water."
    },
    {
      "id": "19.71.5",
      "ref": "Psalms 71:5",
      "text": "For you are my hope, Lord GOD, my confidence from my youth."
    },
    {
      "id": "19.73.26",
      "ref": "Psalms 73:26",
      "text": "My flesh and my heart fails, but God is the strength of my heart and my portion forever."
    },
    {
      "id": "19.84.11",
      "ref": "Psalms 84:11",
      "text": "For the LORD God is a sun and a shield. The LORD will give grace and glory. He withholds no good thing from those who walk blamelessly."
    },
    {
      "id": "19.86.15",
      "ref": "Psalms 86:15",
      "text": "But you, Lord, are a merciful and gracious God, slow to anger, and abundant in loving kindness and truth."
    },
    {
      "id": "19.90.12",
      "ref": "Psalms 90:12",
      "text": "So teach us to count our days, that we may gain a heart of wisdom."
    },
    {
      "id": "19.91.1-2",
      "ref": "Psalms 91:1-2",
      "text": "He who dwells in the secret place of the Most High will rest in the shadow of the Almighty. I will say of the LORD, “He is my refuge and my fortress; my God, in whom I trust.”"
    },
    {
      "id": "19.91.11",
      "ref": "Psalms 91:11",
      "text": "For he will put his angels in charge of you, to guard you in all your ways."
    },
    {
      "id": "19.94.19",
      "ref": "Psalms 94:19",
      "text": "In the multitude of my thoughts within me, your comforts delight my soul."
    },
    {
      "id": "19.100.4-5",
      "ref": "Psalms 100:4-5",
      "text": "Enter into his gates with thanksgiving, and into his courts with praise. Give thanks to him, and bless his name. For the LORD is good. His loving kindness endures forever, his faithfulness to all generations."
    },
    {
      "id": "19.103.2-3",
      "ref": "Psalms 103:2-3",
      "text": "Praise the LORD, my soul, and don’t forget all his benefits, who forgives all your sins, who heals all your diseases,"
    },
    {
      "id": "19.103.8",
      "ref": "Psalms 103:8",
      "text": "The LORD is merciful and gracious, slow to anger, and abundant in loving kindness."
    },
    {
      "id": "19.103.12",
      "ref": "Psalms 103:12",
      "text": "As far as the east is from the west, so far has he removed our transgressions from us."
    },
    {
      "id": "19.107.1",
      "ref": "Psalms 107:1",
      "text": "Give thanks to the LORD, for he is good, for his loving kindness endures forever."
    },
    {
      "id": "19.116.1-2",
      "ref": "Psalms 116:1-2",
      "text": "I love the LORD, because he listens to my voice, and my cries for mercy. Because he has turned his ear to me, therefore I will call on him as long as I live."
    },
    {
      "id": "19.118.24",
      "ref": "Psalms 118:24",
      "text": "This is the day that the LORD has made. We will rejoice and be glad in it!"
    },
    {
      "id": "19.119.105",
      "ref": "Psalms 119:105",
      "text": "Your word is a lamp to my feet, and a light for my path."
    },
    {
      "id": "19.121.1-2",
      "ref": "Psalms 121:1-2",
      "text": "I will lift up my eyes to the hills. Where does my help come from? My help comes from the LORD, who made heaven and earth."
    },
    {
      "id": "19.121.7-8",
      "ref": "Psalms 121:7-8",
      "text": "The LORD will keep you from all evil. He will keep your soul. The LORD will keep your going out and your coming in, from this time forward, and forever more."
    },
    {
      "id": "19.126.3",
      "ref": "Psalms 126:3",
      "text": "The LORD has done great things for us, and we are glad."
    },
    {
      "id": "19.130.5",
      "ref": "Psalms 130:5",
      "text": "I wait for the LORD. My soul waits. I hope in his word."
    },
    {
      "id": "19.133.1",
      "ref": "Psalms 133:1",
      "text": "See how good and how pleasant it is for brothers to live together in unity!"
    },
    {
      "id": "19.136.1",
      "ref": "Psalms 136:1",
      "text": "Give thanks to the LORD, for he is good, for his loving kindness endures forever."
    },
    {
      "id": "19.138.8",
      "ref": "Psalms 138:8",
      "text": "The LORD will fulfill that which concerns me. Your loving kindness, LORD, endures forever. Don’t forsake the works of your own hands."
    },
    {
      "id": "19.139.14",
      "ref": "Psalms 139:14",
      "text": "I will give thanks to you, for I am fearfully and wonderfully made. Your works are wonderful. My soul knows that very well."
    },
    {
      "id": "19.139.23-24",
      "ref": "Psalms 139:23-24",
      "text": "Search me, God, and know my heart. Try me, and know my thoughts. See if there is any wicked way in me, and lead me in the everlasting way."
    },
    {
      "id": "19.143.8",
      "ref": "Psalms 143:8",
      "text": "Cause me to hear your loving kindness in the morning, for I trust in you. Cause me to know the way in which I should walk, for I lift up my soul to you."
    },
    {
      "id": "19.145.8-9",
      "ref": "Psalms 145:8-9",
      "text": "The LORD is gracious, merciful, slow to anger, and of great loving kindness. The LORD is good to all. His tender mercies are over all his works."
    },
    {
      "id": "19.145.18",
      "ref": "Psalms 145:18",
      "text": "The LORD is near to all those who call on him, to all who call on him in truth."
    },
    {
      "id": "19.147.3",
      "ref": "Psalms 147:3",
      "text": "He heals the broken in heart, and binds up their wounds."
    },
    {
      "id": "19.150.6",
      "ref": "Psalms 150:6",
      "text": "Let everything that has breath praise the LORD! Praise the LORD!"
    },
    {
      "id": "20.1.7",
      "ref": "Proverbs 1:7",
      "text": "The fear of the LORD is the beginning of knowledge, but the foolish despise wisdom and instruction."
    },
    {
      "id": "20.2.6",
      "ref": "Proverbs 2:6",
      "text": "For the LORD gives wisdom. Out of his mouth comes knowledge and understanding."
    },
    {
      "id": "20.3.5-6",
      "ref": "Proverbs 3:5-6",
      "text": "Trust in the LORD with all your heart, and don’t lean on your own understanding. In all your ways acknowledge him, and he will make your paths straight."
    },
    {
      "id": "20.3.9-10",
      "ref": "Proverbs 3:9-10",
      "text": "Honor the LORD with your substance, with the first fruits of all your increase; so your barns will be filled with plenty, and your vats will overflow with new wine."
    },
    {
      "id": "20.4.23",
      "ref": "Proverbs 4:23",
      "text": "Keep your heart with all diligence, for out of it is the wellspring of life."
    },
    {
      "id": "20.8.17",
      "ref": "Proverbs 8:17",
      "text": "I love those who love me. Those who seek me diligently will find me."
    },
    {
      "id": "20.10.12",
      "ref": "Proverbs 10:12",
      "text": "Hatred stirs up strife, but love covers all wrongs."
    },
    {
      "id": "20.11.25",
      "ref": "Proverbs 11:25",
      "text": "The liberal soul shall be made fat. He who waters shall be watered also himself."
    },
    {
      "id": "20.12.25",
      "ref": "Proverbs 12:25",
      "text": "Anxiety in a man’s heart weighs it down, but a kind word makes it glad."
    },
    {
      "id": "20.13.20",
      "ref": "Proverbs 13:20",
      "text": "One who walks with wise men grows wise, but a companion of fools suffers harm."
    },
    {
      "id": "20.14.29",
      "ref": "Proverbs 14:29",
      "text": "He who is slow to anger has great understanding, but he who has a quick temper displays folly."
    },
    {
      "id": "20.15.1",
      "ref": "Proverbs 15:1",
      "text": "A gentle answer turns away wrath, but a harsh word stirs up anger."
    },
    {
      "id": "20.16.3",
      "ref": "Proverbs 16:3",
      "text": "Commit your deeds to the LORD, and your plans shall succeed."
    },
    {
      "id": "20.16.9",
      "ref": "Proverbs 16:9",
      "text": "A man’s heart plans his course, but the LORD directs his steps."
    },
    {
      "id": "20.16.24",
      "ref": "Proverbs 16:24",
      "text": "Pleasant words are a honeycomb, sweet to the soul, and health to the bones."
    },
    {
      "id": "20.17.17",
      "ref": "Proverbs 17:17",
      "text": "A friend loves at all times; and a brother is born for adversity."
    },
    {
      "id": "20.18.10",
      "ref": "Proverbs 18:10",
      "text": "The LORD’s name is a strong tower: the righteous run to him, and are safe."
    },
    {
      "id": "20.18.24",
      "ref": "Proverbs 18:24",
      "text": "A man of many companions may be ruined, but there is a friend who sticks closer than a brother."
    },
    {
      "id": "20.19.21",
      "ref": "Proverbs 19:21",
      "text": "There are many plans in a man’s heart, but the LORD’s counsel will prevail."
    },
    {
      "id": "20.21.21",
      "ref": "Proverbs 21:21",
      "text": "He who follows after righteousness and kindness finds life, righteousness, and honor."
    },
    {
      "id": "20.22.6",
      "ref": "Proverbs 22:6",
      "text": "Train up a child in the way he should go, and when he is old he will not depart from it."
    },
    {
      "id": "20.23.18",
      "ref": "Proverbs 23:18",
      "text": "Indeed surely there is a future hope, and your hope will not be cut off."
    },
    {
      "id": "20.24.16",
      "ref": "Proverbs 24:16",
      "text": "for a righteous man falls seven times and rises up again, but the wicked are overthrown by calamity."
    },
    {
      "id": "20.27.17",
      "ref": "Proverbs 27:17",
      "text": "Iron sharpens iron; so a man sharpens his friend’s countenance."
    },
    {
      "id": "20.28.13",
      "ref": "Proverbs 28:13",
      "text": "He who conceals his sins doesn’t prosper, but whoever confesses and renounces them finds mercy."
    },
    {
      "id": "20.29.25",
      "ref": "Proverbs 29:25",
      "text": "The fear of man proves to be a snare, but whoever puts his trust in the LORD is kept safe."
    },
    {
      "id": "20.30.5",
      "ref": "Proverbs 30:5",
      "text": "“Every word of God is flawless. He is a shield to those who take refuge in him."
    },
    {
      "id": "20.31.25",
      "ref": "Proverbs 31:25",
      "text": "Strength and dignity are her clothing. She laughs at the time to come."
    },
    {
      "id": "21.3.1",
      "ref": "Ecclesiastes 3:1",
      "text": "For everything there is a season, and a time for every purpose under heaven:"
    },
    {
      "id": "21.3.11",
      "ref": "Ecclesiastes 3:11",
      "text": "He has made everything beautiful in its time. He has also set eternity in their hearts, yet so that man can’t find out the work that God has done from the beginning even to the end."
    },
    {
      "id": "21.4.9-10",
      "ref": "Ecclesiastes 4:9-10",
      "text": "Two are better than one, because they have a good reward for their labor. For if they fall, the one will lift up his fellow; but woe to him who is alone when he falls, and doesn’t have another to lift him up."
    },
    {
      "id": "21.12.13",
      "ref": "Ecclesiastes 12:13",
      "text": "This is the end of the matter. All has been heard. Fear God and keep his commandments; for this is the whole duty of man."
    },
    {
      "id": "23.1.18",
      "ref": "Isaiah 1:18",
      "text": "“Come now, and let’s reason together,” says the LORD: “Though your sins are as scarlet, they shall be as white as snow. Though they are red like crimson, they shall be as wool."
    },
    {
      "id": "23.6.8",
      "ref": "Isaiah 6:8",
      "text": "I heard the Lord’s voice, saying, “Whom shall I send, and who will go for us?” Then I said, “Here I am. Send me!”"
    },
    {
      "id": "23.9.6",
      "ref": "Isaiah 9:6",
      "text": "For a child is born to us. A son is given to us; and the government will be on his shoulders. His name will be called Wonderful Counselor, Mighty God, Everlasting Father, Prince of Peace."
    },
    {
      "id": "23.12.2",
      "ref": "Isaiah 12:2",
      "text": "Behold, God is my salvation. I will trust, and will not be afraid; for the LORD, the LORD, is my strength and song; and he has become my salvation.”"
    },
    {
      "id": "23.25.1",
      "ref": "Isaiah 25:1",
      "text": "The LORD, you are my God. I will exalt you! I will praise your name, for you have done wonderful things, things planned long ago, in complete faithfulness and truth."
    },
    {
      "id": "23.26.3",
      "ref": "Isaiah 26:3",
      "text": "You will keep whoever’s mind is steadfast in perfect peace, because he trusts in you."
    },
    {
      "id": "23.30.15",
      "ref": "Isaiah 30:15",
      "text": "For thus said the Lord GOD, the Holy One of Israel, “You will be saved in returning and rest. Your strength will be in quietness and in confidence.” You refused,"
    },
    {
      "id": "23.30.21",
      "ref": "Isaiah 30:21",
      "text": "and when you turn to the right hand, and when you turn to the left, your ears will hear a voice behind you, saying, “This is the way. Walk in it.”"
    },
    {
      "id": "23.32.17",
      "ref": "Isaiah 32:17",
      "text": "The work of righteousness will be peace, and the effect of righteousness, quietness and confidence forever."
    },
    {
      "id": "23.40.8",
      "ref": "Isaiah 40:8",
      "text": "The grass withers, the flower fades; but the word of our God stands forever.”"
    },
    {
      "id": "23.40.28",
      "ref": "Isaiah 40:28",
      "text": "Haven’t you known? Haven’t you heard? The everlasting God, the LORD, the Creator of the ends of the earth, doesn’t faint. He isn’t weary. His understanding is unsearchable."
    },
    {
      "id": "23.40.29",
      "ref": "Isaiah 40:29",
      "text": "He gives power to the weak. He increases the strength of him who has no might."
    },
    {
      "id": "23.40.31",
      "ref": "Isaiah 40:31",
      "text": "but those who wait for the LORD will renew their strength. They will mount up with wings like eagles. They will run, and not be weary. They will walk, and not faint."
    },
    {
      "id": "23.41.10",
      "ref": "Isaiah 41:10",
      "text": "Don’t you be afraid, for I am with you. Don’t be dismayed, for I am your God. I will strengthen you. Yes, I will help you. Yes, I will uphold you with the right hand of my righteousness."
    },
    {
      "id": "23.41.13",
      "ref": "Isaiah 41:13",
      "text": "For I, the LORD your God, will hold your right hand, saying to you, ‘Don’t be afraid. I will help you.’"
    },
    {
      "id": "23.43.1",
      "ref": "Isaiah 43:1",
      "text": "But now the LORD who created you, Jacob, and he who formed you, Israel, says: “Don’t be afraid, for I have redeemed you. I have called you by your name. You are mine."
    },
    {
      "id": "23.43.2",
      "ref": "Isaiah 43:2",
      "text": "When you pass through the waters, I will be with you, and through the rivers, they will not overflow you. When you walk through the fire, you will not be burned, and flame will not scorch you."
    },
    {
      "id": "23.43.19",
      "ref": "Isaiah 43:19",
      "text": "Behold, I will do a new thing. It springs out now. Don’t you know it? I will even make a way in the wilderness, and rivers in the desert."
    },
    {
      "id": "23.46.4",
      "ref": "Isaiah 46:4",
      "text": "Even to old age I am he, and even to gray hairs I will carry you. I have made, and I will bear. Yes, I will carry, and will deliver."
    },
    {
      "id": "23.49.15-16",
      "ref": "Isaiah 49:15-16",
      "text": "“Can a woman forget her nursing child, that she should not have compassion on the son of her womb? Yes, these may forget, yet I will not forget you! Behold, I have engraved you on the palms of my hands. Your walls are continually before me."
    },
    {
      "id": "23.53.5",
      "ref": "Isaiah 53:5",
      "text": "But he was pierced for our transgressions. He was crushed for our iniquities. The punishment that brought our peace was on him; and by his wounds we are healed."
    },
    {
      "id": "23.54.10",
      "ref": "Isaiah 54:10",
      "text": "For the mountains may depart, and the hills be removed, but my loving kindness will not depart from you, and my covenant of peace will not be removed,” says the LORD who has mercy on you."
    },
    {
      "id": "23.55.8-9",
      "ref": "Isaiah 55:8-9",
      "text": "“For my thoughts are not your thoughts, and your ways are not my ways,” says the LORD. “For as the heavens are higher than the earth, so are my ways higher than your ways, and my thoughts than your thoughts."
    },
    {
      "id": "23.55.11",
      "ref": "Isaiah 55:11",
      "text": "so is my word that goes out of my mouth: it will not return to me void, but it will accomplish that which I please, and it will prosper in the thing I sent it to do."
    },
    {
      "id": "23.58.11",
      "ref": "Isaiah 58:11",
      "text": "and the LORD will guide you continually, satisfy your soul in dry places, and make your bones strong. You will be like a watered garden, and like a spring of water whose waters don’t fail."
    },
    {
      "id": "23.61.1",
      "ref": "Isaiah 61:1",
      "text": "The Lord GOD’s Spirit is on me, because the LORD has anointed me to preach good news to the humble. He has sent me to bind up the broken hearted, to proclaim liberty to the captives and release to those who are bound,"
    },
    {
      "id": "23.64.8",
      "ref": "Isaiah 64:8",
      "text": "But now, LORD, you are our Father. We are the clay and you our potter. We all are the work of your hand."
    },
    {
      "id": "23.66.13",
      "ref": "Isaiah 66:13",
      "text": "As one whom his mother comforts, so I will comfort you. You will be comforted in Jerusalem.”"
    },
    {
      "id": "24.1.5",
      "ref": "Jeremiah 1:5",
      "text": "“Before I formed you in the womb, I knew you. Before you were born, I sanctified you. I have appointed you a prophet to the nations.”"
    },
    {
      "id": "24.9.23-24",
      "ref": "Jeremiah 9:23-24",
      "text": "The LORD says, “Don’t let the wise man glory in his wisdom. Don’t let the mighty man glory in his might. Don’t let the rich man glory in his riches. But let him who glories glory in this, that he has understanding, and knows me, that I am the LORD who exercises loving kindness, justice, and righteousness in the earth, for I delight in these things,” says the LORD."
    },
    {
      "id": "24.15.16",
      "ref": "Jeremiah 15:16",
      "text": "Your words were found, and I ate them. Your words were to me a joy and the rejoicing of my heart, for I am called by your name, LORD, God of Armies."
    },
    {
      "id": "24.17.7-8",
      "ref": "Jeremiah 17:7-8",
      "text": "“Blessed is the man who trusts in the LORD, and whose confidence is in the LORD. For he will be as a tree planted by the waters, who spreads out its roots by the river, and will not fear when heat comes, but its leaf will be green, and will not be concerned in the year of drought. It won’t cease from yielding fruit."
    },
    {
      "id": "24.17.14",
      "ref": "Jeremiah 17:14",
      "text": "Heal me, O LORD, and I will be healed. Save me, and I will be saved; for you are my praise."
    },
    {
      "id": "24.29.11",
      "ref": "Jeremiah 29:11",
      "text": "For I know the thoughts that I think toward you,” says the LORD, “thoughts of peace, and not of evil, to give you hope and a future."
    },
    {
      "id": "24.29.12-13",
      "ref": "Jeremiah 29:12-13",
      "text": "You shall call on me, and you shall go and pray to me, and I will listen to you. You shall seek me and find me, when you search for me with all your heart."
    },
    {
      "id": "24.31.3",
      "ref": "Jeremiah 31:3",
      "text": "The LORD appeared of old to me, saying, “Yes, I have loved you with an everlasting love. Therefore I have drawn you with loving kindness."
    },
    {
      "id": "24.32.17",
      "ref": "Jeremiah 32:17",
      "text": "“Ah Lord GOD! Behold, you have made the heavens and the earth by your great power and by your outstretched arm. There is nothing too hard for you."
    },
    {
      "id": "24.33.3",
      "ref": "Jeremiah 33:3",
      "text": "‘Call to me, and I will answer you, and will show you great and difficult things, which you don’t know.’"
    },
    {
      "id": "25.3.22-23",
      "ref": "Lamentations 3:22-23",
      "text": "It is because of the LORD’s loving kindnesses that we are not consumed, because his mercies don’t fail. They are new every morning. Great is your faithfulness."
    },
    {
      "id": "25.3.25",
      "ref": "Lamentations 3:25",
      "text": "The LORD is good to those who wait for him, to the soul who seeks him."
    },
    {
      "id": "26.34.16",
      "ref": "Ezekiel 34:16",
      "text": "“I will seek that which was lost, and will bring back that which was driven away, and will bind up that which was broken, and will strengthen that which was sick; but I will destroy the fat and the strong. I will feed them in justice.”’"
    },
    {
      "id": "26.36.26",
      "ref": "Ezekiel 36:26",
      "text": "I will also give you a new heart, and I will put a new spirit within you. I will take away the stony heart out of your flesh, and I will give you a heart of flesh."
    },
    {
      "id": "27.3.17",
      "ref": "Daniel 3:17",
      "text": "If it happens, our God whom we serve is able to deliver us from the burning fiery furnace; and he will deliver us out of your hand, O king."
    },
    {
      "id": "27.12.3",
      "ref": "Daniel 12:3",
      "text": "Those who are wise will shine as the brightness of the expanse. Those who turn many to righteousness will shine as the stars forever and ever."
    },
    {
      "id": "28.6.3",
      "ref": "Hosea 6:3",
      "text": "Let’s acknowledge the LORD. Let’s press on to know the LORD. As surely as the sun rises, the LORD will appear. He will come to us like the rain, like the spring rain that waters the earth.”"
    },
    {
      "id": "29.2.13",
      "ref": "Joel 2:13",
      "text": "Tear your heart and not your garments, and turn to the LORD, your God; for he is gracious and merciful, slow to anger, and abundant in loving kindness, and relents from sending calamity."
    },
    {
      "id": "29.2.25",
      "ref": "Joel 2:25",
      "text": "I will restore to you the years that the swarming locust has eaten, the great locust, the grasshopper, and the caterpillar, my great army, which I sent among you."
    },
    {
      "id": "30.5.24",
      "ref": "Amos 5:24",
      "text": "But let justice roll on like rivers, and righteousness like a mighty stream."
    },
    {
      "id": "33.6.8",
      "ref": "Micah 6:8",
      "text": "He has shown you, O man, what is good. What does the LORD require of you, but to act justly, to love mercy, and to walk humbly with your God?"
    },
    {
      "id": "33.7.7",
      "ref": "Micah 7:7",
      "text": "But as for me, I will look to the LORD. I will wait for the God of my salvation. My God will hear me."
    },
    {
      "id": "33.7.18",
      "ref": "Micah 7:18",
      "text": "Who is a God like you, who pardons iniquity, and passes over the disobedience of the remnant of his heritage? He doesn’t retain his anger forever, because he delights in loving kindness."
    },
    {
      "id": "34.1.7",
      "ref": "Nahum 1:7",
      "text": "The LORD is good, a stronghold in the day of trouble; and he knows those who take refuge in him."
    },
    {
      "id": "35.2.4",
      "ref": "Habakkuk 2:4",
      "text": "Behold, his soul is puffed up. It is not upright in him, but the righteous will live by his faith."
    },
    {
      "id": "35.3.19",
      "ref": "Habakkuk 3:19",
      "text": "GOD, the Lord, is my strength. He makes my feet like deer’s feet, and enables me to go in high places. For the music director, on my stringed instruments."
    },
    {
      "id": "36.3.17",
      "ref": "Zephaniah 3:17",
      "text": "The LORD, your God, is among you, a mighty one who will save. He will rejoice over you with joy. He will calm you in his love. He will rejoice over you with singing."
    },
    {
      "id": "37.2.4",
      "ref": "Haggai 2:4",
      "text": "Yet now be strong, Zerubbabel,’ says the LORD. ‘Be strong, Joshua son of Jehozadak, the high priest. Be strong, all you people of the land,’ says the LORD, ‘and work, for I am with you,’ says the LORD of Armies."
    },
    {
      "id": "38.4.6",
      "ref": "Zechariah 4:6",
      "text": "Then he answered and spoke to me, saying, “This is the LORD’s word to Zerubbabel, saying, ‘Not by might, nor by power, but by my Spirit,’ says the LORD of Armies."
    },
    {
      "id": "38.9.9",
      "ref": "Zechariah 9:9",
      "text": "Rejoice greatly, daughter of Zion! Shout, daughter of Jerusalem! Behold, your King comes to you! He is righteous, and having salvation; lowly, and riding on a donkey, even on a colt, the foal of a donkey."
    },
    {
      "id": "39.3.6",
      "ref": "Malachi 3:6",
      "text": "“For I, the LORD, don’t change; therefore you, sons of Jacob, are not consumed."
    },
    {
      "id": "39.3.10",
      "ref": "Malachi 3:10",
      "text": "Bring the whole tithe into the storehouse, that there may be food in my house, and test me now in this,” says the LORD of Armies, “if I will not open you the windows of heaven, and pour you out a blessing, that there will not be enough room for."
    },
    {
      "id": "40.4.4",
      "ref": "Matthew 4:4",
      "text": "But he answered, “It is written, ‘Man shall not live by bread alone, but by every word that proceeds out of God’s mouth.’”"
    },
    {
      "id": "40.5.3-4",
      "ref": "Matthew 5:3-4",
      "text": "“Blessed are the poor in spirit, for theirs is the Kingdom of Heaven. Blessed are those who mourn, for they shall be comforted."
    },
    {
      "id": "40.5.9",
      "ref": "Matthew 5:9",
      "text": "Blessed are the peacemakers, for they shall be called children of God."
    },
    {
      "id": "40.5.14",
      "ref": "Matthew 5:14",
      "text": "“You are the light of the world. A city located on a hill can’t be hidden."
    },
    {
      "id": "40.5.16",
      "ref": "Matthew 5:16",
      "text": "Even so, let your light shine before men, that they may see your good works and glorify your Father who is in heaven."
    },
    {
      "id": "40.5.44",
      "ref": "Matthew 5:44",
      "text": "But I tell you, love your enemies, bless those who curse you, do good to those who hate you, and pray for those who mistreat you and persecute you,"
    },
    {
      "id": "40.6.19-21",
      "ref": "Matthew 6:19-21",
      "text": "“Don’t lay up treasures for yourselves on the earth, where moth and rust consume, and where thieves break through and steal; but lay up for yourselves treasures in heaven, where neither moth nor rust consume, and where thieves don’t break through and steal; for where your treasure is, there your heart will be also."
    },
    {
      "id": "40.6.26",
      "ref": "Matthew 6:26",
      "text": "See the birds of the sky, that they don’t sow, neither do they reap, nor gather into barns. Your heavenly Father feeds them. Aren’t you of much more value than they?"
    },
    {
      "id": "40.6.33",
      "ref": "Matthew 6:33",
      "text": "But seek first God’s Kingdom and his righteousness; and all these things will be given to you as well."
    },
    {
      "id": "40.6.34",
      "ref": "Matthew 6:34",
      "text": "Therefore don’t be anxious for tomorrow, for tomorrow will be anxious for itself. Each day’s own evil is sufficient."
    },
    {
      "id": "40.7.7",
      "ref": "Matthew 7:7",
      "text": "“Ask, and it will be given you. Seek, and you will find. Knock, and it will be opened for you."
    },
    {
      "id": "40.7.12",
      "ref": "Matthew 7:12",
      "text": "Therefore, whatever you desire for men to do to you, you shall also do to them; for this is the law and the prophets."
    },
    {
      "id": "40.9.37-38",
      "ref": "Matthew 9:37-38",
      "text": "Then he said to his disciples, “The harvest indeed is plentiful, but the laborers are few. Pray therefore that the Lord of the harvest will send out laborers into his harvest.”"
    },
    {
      "id": "40.10.29-31",
      "ref": "Matthew 10:29-31",
      "text": "“Aren’t two sparrows sold for an assarion coin? Not one of them falls to the ground apart from your Father’s will. But the very hairs of your head are all numbered. Therefore don’t be afraid. You are of more value than many sparrows."
    },
    {
      "id": "40.11.28-30",
      "ref": "Matthew 11:28-30",
      "text": "“Come to me, all you who labor and are heavily burdened, and I will give you rest. Take my yoke upon you and learn from me, for I am gentle and humble in heart; and you will find rest for your souls. For my yoke is easy, and my burden is light.”"
    },
    {
      "id": "40.16.24",
      "ref": "Matthew 16:24",
      "text": "Then Jesus said to his disciples, “If anyone desires to come after me, let him deny himself, take up his cross, and follow me."
    },
    {
      "id": "40.18.20",
      "ref": "Matthew 18:20",
      "text": "For where two or three are gathered together in my name, there I am in the middle of them.”"
    },
    {
      "id": "40.19.26",
      "ref": "Matthew 19:26",
      "text": "Looking at them, Jesus said, “With men this is impossible, but with God all things are possible.”"
    },
    {
      "id": "40.21.22",
      "ref": "Matthew 21:22",
      "text": "All things, whatever you ask in prayer, believing, you will receive.”"
    },
    {
      "id": "40.22.37-39",
      "ref": "Matthew 22:37-39",
      "text": "Jesus said to him, “‘You shall love the Lord your God with all your heart, with all your soul, and with all your mind.’ This is the first and great commandment. A second likewise is this, ‘You shall love your neighbor as yourself.’"
    },
    {
      "id": "40.25.40",
      "ref": "Matthew 25:40",
      "text": "“The King will answer them, ‘Most certainly I tell you, because you did it to one of the least of these my brothers, you did it to me.’"
    },
    {
      "id": "40.28.19-20",
      "ref": "Matthew 28:19-20",
      "text": "Go and make disciples of all nations, baptizing them in the name of the Father and of the Son and of the Holy Spirit, teaching them to observe all things that I commanded you. Behold, I am with you always, even to the end of the age.” Amen."
    },
    {
      "id": "41.4.39",
      "ref": "Mark 4:39",
      "text": "He awoke and rebuked the wind, and said to the sea, “Peace! Be still!” The wind ceased and there was a great calm."
    },
    {
      "id": "41.5.36",
      "ref": "Mark 5:36",
      "text": "But Jesus, when he heard the message spoken, immediately said to the ruler of the synagogue, “Don’t be afraid, only believe.”"
    },
    {
      "id": "41.6.31",
      "ref": "Mark 6:31",
      "text": "He said to them, “Come away into a deserted place, and rest awhile.” For there were many coming and going, and they had no leisure so much as to eat."
    },
    {
      "id": "41.9.23",
      "ref": "Mark 9:23",
      "text": "Jesus said to him, “If you can believe, all things are possible to him who believes.”"
    },
    {
      "id": "41.10.27",
      "ref": "Mark 10:27",
      "text": "Jesus, looking at them, said, “With men it is impossible, but not with God, for all things are possible with God.”"
    },
    {
      "id": "41.10.45",
      "ref": "Mark 10:45",
      "text": "For the Son of Man also came not to be served but to serve, and to give his life as a ransom for many.”"
    },
    {
      "id": "41.11.24",
      "ref": "Mark 11:24",
      "text": "Therefore I tell you, all things whatever you pray and ask for, believe that you have received them, and you shall have them."
    },
    {
      "id": "41.12.30-31",
      "ref": "Mark 12:30-31",
      "text": "You shall love the Lord your God with all your heart, with all your soul, with all your mind, and with all your strength.’ This is the first commandment. The second is like this: ‘You shall love your neighbor as yourself.’ There is no other commandment greater than these.”"
    },
    {
      "id": "41.16.15",
      "ref": "Mark 16:15",
      "text": "He said to them, “Go into all the world and preach the Good News to the whole creation."
    },
    {
      "id": "42.1.37",
      "ref": "Luke 1:37",
      "text": "For nothing spoken by God is impossible.”"
    },
    {
      "id": "42.1.78-79",
      "ref": "Luke 1:78-79",
      "text": "because of the tender mercy of our God, by which the dawn from on high will visit us, to shine on those who sit in darkness and the shadow of death; to guide our feet into the way of peace.”"
    },
    {
      "id": "42.2.10-11",
      "ref": "Luke 2:10-11",
      "text": "The angel said to them, “Don’t be afraid, for behold, I bring you good news of great joy which will be to all the people. For there is born to you today, in David’s city, a Savior, who is Christ the Lord."
    },
    {
      "id": "42.2.14",
      "ref": "Luke 2:14",
      "text": "“Glory to God in the highest, on earth peace, good will toward men.”"
    },
    {
      "id": "42.6.31",
      "ref": "Luke 6:31",
      "text": "“As you would like people to do to you, do exactly so to them."
    },
    {
      "id": "42.6.36",
      "ref": "Luke 6:36",
      "text": "“Therefore be merciful, even as your Father is also merciful."
    },
    {
      "id": "42.6.38",
      "ref": "Luke 6:38",
      "text": "“Give, and it will be given to you: good measure, pressed down, shaken together, and running over, will be given to you. For with the same measure you measure it will be measured back to you.”"
    },
    {
      "id": "42.10.27",
      "ref": "Luke 10:27",
      "text": "He answered, “You shall love the Lord your God with all your heart, with all your soul, with all your strength, and with all your mind; and your neighbor as yourself.”"
    },
    {
      "id": "42.11.9",
      "ref": "Luke 11:9",
      "text": "“I tell you, keep asking, and it will be given you. Keep seeking, and you will find. Keep knocking, and it will be opened to you."
    },
    {
      "id": "42.12.7",
      "ref": "Luke 12:7",
      "text": "But the very hairs of your head are all counted. Therefore don’t be afraid. You are of more value than many sparrows."
    },
    {
      "id": "42.12.32",
      "ref": "Luke 12:32",
      "text": "“Don’t be afraid, little flock, for it is your Father’s good pleasure to give you the Kingdom."
    },
    {
      "id": "42.15.7",
      "ref": "Luke 15:7",
      "text": "I tell you that even so there will be more joy in heaven over one sinner who repents, than over ninety-nine righteous people who need no repentance."
    },
    {
      "id": "42.18.27",
      "ref": "Luke 18:27",
      "text": "But he said, “The things which are impossible with men are possible with God.”"
    },
    {
      "id": "42.21.33",
      "ref": "Luke 21:33",
      "text": "Heaven and earth will pass away, but my words will by no means pass away."
    },
    {
      "id": "43.1.1",
      "ref": "John 1:1",
      "text": "In the beginning was the Word, and the Word was with God, and the Word was God."
    },
    {
      "id": "43.1.5",
      "ref": "John 1:5",
      "text": "The light shines in the darkness, and the darkness hasn’t overcome it."
    },
    {
      "id": "43.1.12",
      "ref": "John 1:12",
      "text": "But as many as received him, to them he gave the right to become God’s children, to those who believe in his name:"
    },
    {
      "id": "43.3.16",
      "ref": "John 3:16",
      "text": "For God so loved the world, that he gave his only born Son, that whoever believes in him should not perish, but have eternal life."
    },
    {
      "id": "43.3.17",
      "ref": "John 3:17",
      "text": "For God didn’t send his Son into the world to judge the world, but that the world should be saved through him."
    },
    {
      "id": "43.4.14",
      "ref": "John 4:14",
      "text": "but whoever drinks of the water that I will give him will never thirst again; but the water that I will give him will become in him a well of water springing up to eternal life.”"
    },
    {
      "id": "43.6.35",
      "ref": "John 6:35",
      "text": "Jesus said to them, “I am the bread of life. Whoever comes to me will not be hungry, and whoever believes in me will never be thirsty."
    },
    {
      "id": "43.8.12",
      "ref": "John 8:12",
      "text": "Again, therefore, Jesus spoke to them, saying, “I am the light of the world. He who follows me will not walk in the darkness, but will have the light of life.”"
    },
    {
      "id": "43.8.32",
      "ref": "John 8:32",
      "text": "You will know the truth, and the truth will make you free.”"
    },
    {
      "id": "43.10.9",
      "ref": "John 10:9",
      "text": "I am the door. If anyone enters in by me, he will be saved, and will go in and go out and will find pasture."
    },
    {
      "id": "43.10.14-15",
      "ref": "John 10:14-15",
      "text": "I am the good shepherd. I know my own, and I’m known by my own; even as the Father knows me, and I know the Father. I lay down my life for the sheep."
    },
    {
      "id": "43.10.27-28",
      "ref": "John 10:27-28",
      "text": "My sheep hear my voice, and I know them, and they follow me. I give eternal life to them. They will never perish, and no one will snatch them out of my hand."
    },
    {
      "id": "43.11.25-26",
      "ref": "John 11:25-26",
      "text": "Jesus said to her, “I am the resurrection and the life. He who believes in me will still live, even if he dies. Whoever lives and believes in me will never die. Do you believe this?”"
    },
    {
      "id": "43.13.34-35",
      "ref": "John 13:34-35",
      "text": "A new commandment I give to you, that you love one another. Just as I have loved you, you also love one another. By this everyone will know that you are my disciples, if you have love for one another.”"
    },
    {
      "id": "43.14.1",
      "ref": "John 14:1",
      "text": "“Don’t let your heart be troubled. Believe in God. Believe also in me."
    },
    {
      "id": "43.14.6",
      "ref": "John 14:6",
      "text": "Jesus said to him, “I am the way, the truth, and the life. No one comes to the Father, except through me."
    },
    {
      "id": "43.14.16-17",
      "ref": "John 14:16-17",
      "text": "I will pray to the Father, and he will give you another Counselor, that he may be with you forever: the Spirit of truth, whom the world can’t receive, for it doesn’t see him and doesn’t know him. You know him, for he lives with you and will be in you."
    },
    {
      "id": "43.14.27",
      "ref": "John 14:27",
      "text": "Peace I leave with you. My peace I give to you; not as the world gives, I give to you. Don’t let your heart be troubled, neither let it be fearful."
    },
    {
      "id": "43.15.5",
      "ref": "John 15:5",
      "text": "I am the vine. You are the branches. He who remains in me and I in him bears much fruit, for apart from me you can do nothing."
    },
    {
      "id": "43.15.12",
      "ref": "John 15:12",
      "text": "“This is my commandment, that you love one another, even as I have loved you."
    },
    {
      "id": "43.15.13",
      "ref": "John 15:13",
      "text": "Greater love has no one than this, that someone lay down his life for his friends."
    },
    {
      "id": "43.16.33",
      "ref": "John 16:33",
      "text": "I have told you these things, that in me you may have peace. In the world you have trouble; but cheer up! I have overcome the world.”"
    },
    {
      "id": "43.17.3",
      "ref": "John 17:3",
      "text": "This is eternal life, that they should know you, the only true God, and him whom you sent, Jesus Christ."
    },
    {
      "id": "43.20.29",
      "ref": "John 20:29",
      "text": "Jesus said to him, “Because you have seen me, you have believed. Blessed are those who have not seen and have believed.”"
    },
    {
      "id": "44.1.8",
      "ref": "Acts 1:8",
      "text": "But you will receive power when the Holy Spirit has come upon you. You will be witnesses to me in Jerusalem, in all Judea and Samaria, and to the uttermost parts of the earth.”"
    },
    {
      "id": "44.2.21",
      "ref": "Acts 2:21",
      "text": "It will be that whoever will call on the name of the Lord will be saved.’"
    },
    {
      "id": "44.2.38",
      "ref": "Acts 2:38",
      "text": "Peter said to them, “Repent and be baptized, every one of you, in the name of Jesus Christ for the forgiveness of sins, and you will receive the gift of the Holy Spirit."
    },
    {
      "id": "44.4.12",
      "ref": "Acts 4:12",
      "text": "There is salvation in no one else, for there is no other name under heaven that is given among men, by which we must be saved!”"
    },
    {
      "id": "44.16.31",
      "ref": "Acts 16:31",
      "text": "They said, “Believe in the Lord Jesus Christ, and you will be saved, you and your household.”"
    },
    {
      "id": "44.17.27-28",
      "ref": "Acts 17:27-28",
      "text": "that they should seek the Lord, if perhaps they might reach out for him and find him, though he is not far from each one of us. ‘For in him we live, move, and have our being.’ As some of your own poets have said, ‘For we are also his offspring.’"
    },
    {
      "id": "44.20.35",
      "ref": "Acts 20:35",
      "text": "In all things I gave you an example, that so laboring you ought to help the weak, and to remember the words of the Lord Jesus, that he himself said, ‘It is more blessed to give than to receive.’ ”"
    },
    {
      "id": "45.1.16",
      "ref": "Romans 1:16",
      "text": "For I am not ashamed of the Good News of Christ, because it is the power of God for salvation for everyone who believes, for the Jew first, and also for the Greek."
    },
    {
      "id": "45.3.23-24",
      "ref": "Romans 3:23-24",
      "text": "for all have sinned, and fall short of the glory of God; being justified freely by his grace through the redemption that is in Christ Jesus,"
    },
    {
      "id": "45.5.1",
      "ref": "Romans 5:1",
      "text": "Being therefore justified by faith, we have peace with God through our Lord Jesus Christ;"
    },
    {
      "id": "45.5.3-5",
      "ref": "Romans 5:3-5",
      "text": "Not only this, but we also rejoice in our sufferings, knowing that suffering produces perseverance; and perseverance, proven character; and proven character, hope; and hope doesn’t disappoint us, because God’s love has been poured into our hearts through the Holy Spirit who was given to us."
    },
    {
      "id": "45.5.8",
      "ref": "Romans 5:8",
      "text": "But God commends his own love toward us, in that while we were yet sinners, Christ died for us."
    },
    {
      "id": "45.6.23",
      "ref": "Romans 6:23",
      "text": "For the wages of sin is death, but the free gift of God is eternal life in Christ Jesus our Lord."
    },
    {
      "id": "45.8.1",
      "ref": "Romans 8:1",
      "text": "There is therefore now no condemnation to those who are in Christ Jesus, who don’t walk according to the flesh, but according to the Spirit."
    },
    {
      "id": "45.8.18",
      "ref": "Romans 8:18",
      "text": "For I consider that the sufferings of this present time are not worthy to be compared with the glory which will be revealed toward us."
    },
    {
      "id": "45.8.26",
      "ref": "Romans 8:26",
      "text": "In the same way, the Spirit also helps our weaknesses, for we don’t know how to pray as we ought. But the Spirit himself makes intercession for us with groanings which can’t be uttered."
    },
    {
      "id": "45.8.28",
      "ref": "Romans 8:28",
      "text": "We know that all things work together for good for those who love God, for those who are called according to his purpose."
    },
    {
      "id": "45.8.31",
      "ref": "Romans 8:31",
      "text": "What then shall we say about these things? If God is for us, who can be against us?"
    },
    {
      "id": "45.8.37",
      "ref": "Romans 8:37",
      "text": "No, in all these things we are more than conquerors through him who loved us."
    },
    {
      "id": "45.8.38-39",
      "ref": "Romans 8:38-39",
      "text": "For I am persuaded that neither death, nor life, nor angels, nor principalities, nor things present, nor things to come, nor powers, nor height, nor depth, nor any other created thing will be able to separate us from God’s love which is in Christ Jesus our Lord."
    },
    {
      "id": "45.10.9",
      "ref": "Romans 10:9",
      "text": "that if you will confess with your mouth that Jesus is Lord and believe in your heart that God raised him from the dead, you will be saved."
    },
    {
      "id": "45.10.17",
      "ref": "Romans 10:17",
      "text": "So faith comes by hearing, and hearing by the word of God."
    },
    {
      "id": "45.12.1",
      "ref": "Romans 12:1",
      "text": "Therefore I urge you, brothers, by the mercies of God, to present your bodies a living sacrifice, holy, acceptable to God, which is your spiritual service."
    },
    {
      "id": "45.12.2",
      "ref": "Romans 12:2",
      "text": "Don’t be conformed to this world, but be transformed by the renewing of your mind, so that you may prove what is the good, well-pleasing, and perfect will of God."
    },
    {
      "id": "45.12.9-10",
      "ref": "Romans 12:9-10",
      "text": "Let love be without hypocrisy. Abhor that which is evil. Cling to that which is good. In love of the brothers be tenderly affectionate to one another; in honor prefer one another,"
    },
    {
      "id": "45.12.12",
      "ref": "Romans 12:12",
      "text": "rejoicing in hope, enduring in troubles, continuing steadfastly in prayer,"
    },
    {
      "id": "45.12.21",
      "ref": "Romans 12:21",
      "text": "Don’t be overcome by evil, but overcome evil with good."
    },
    {
      "id": "45.13.8",
      "ref": "Romans 13:8",
      "text": "Owe no one anything, except to love one another; for he who loves his neighbor has fulfilled the law."
    },
    {
      "id": "45.15.13",
      "ref": "Romans 15:13",
      "text": "Now may the God of hope fill you with all joy and peace in believing, that you may abound in hope in the power of the Holy Spirit."
    },
    {
      "id": "46.1.9",
      "ref": "1 Corinthians 1:9",
      "text": "God is faithful, through whom you were called into the fellowship of his Son, Jesus Christ our Lord."
    },
    {
      "id": "46.2.9",
      "ref": "1 Corinthians 2:9",
      "text": "But as it is written, “Things which an eye didn’t see, and an ear didn’t hear, which didn’t enter into the heart of man, these God has prepared for those who love him.”"
    },
    {
      "id": "46.3.16",
      "ref": "1 Corinthians 3:16",
      "text": "Don’t you know that you are God’s temple and that God’s Spirit lives in you?"
    },
    {
      "id": "46.6.19-20",
      "ref": "1 Corinthians 6:19-20",
      "text": "Or don’t you know that your body is a temple of the Holy Spirit who is in you, whom you have from God? You are not your own, for you were bought with a price. Therefore glorify God in your body and in your spirit, which are God’s."
    },
    {
      "id": "46.9.24",
      "ref": "1 Corinthians 9:24",
      "text": "Don’t you know that those who run in a race all run, but one receives the prize? Run like that, so that you may win."
    },
    {
      "id": "46.10.13",
      "ref": "1 Corinthians 10:13",
      "text": "No temptation has taken you except what is common to man. God is faithful, who will not allow you to be tempted above what you are able, but will with the temptation also make the way of escape, that you may be able to endure it."
    },
    {
      "id": "46.10.31",
      "ref": "1 Corinthians 10:31",
      "text": "Whether therefore you eat or drink, or whatever you do, do all to the glory of God."
    },
    {
      "id": "46.12.12",
      "ref": "1 Corinthians 12:12",
      "text": "For as the body is one and has many members, and all the members of the body, being many, are one body; so also is Christ."
    },
    {
      "id": "46.13.4-5",
      "ref": "1 Corinthians 13:4-5",
      "text": "Love is patient and is kind. Love doesn’t envy. Love doesn’t brag, is not proud, doesn’t behave itself inappropriately, doesn’t seek its own way, is not provoked, takes no account of evil;"
    },
    {
      "id": "46.13.7",
      "ref": "1 Corinthians 13:7",
      "text": "bears all things, believes all things, hopes all things, and endures all things."
    },
    {
      "id": "46.13.13",
      "ref": "1 Corinthians 13:13",
      "text": "But now faith, hope, and love remain—these three. The greatest of these is love."
    },
    {
      "id": "46.15.57",
      "ref": "1 Corinthians 15:57",
      "text": "But thanks be to God, who gives us the victory through our Lord Jesus Christ."
    },
    {
      "id": "46.15.58",
      "ref": "1 Corinthians 15:58",
      "text": "Therefore, my beloved brothers, be steadfast, immovable, always abounding in the Lord’s work, because you know that your labor is not in vain in the Lord."
    },
    {
      "id": "46.16.13-14",
      "ref": "1 Corinthians 16:13-14",
      "text": "Watch! Stand firm in the faith! Be courageous! Be strong! Let all that you do be done in love."
    },
    {
      "id": "47.1.3-4",
      "ref": "2 Corinthians 1:3-4",
      "text": "Blessed be the God and Father of our Lord Jesus Christ, the Father of mercies and God of all comfort, who comforts us in all our affliction, that we may be able to comfort those who are in any affliction, through the comfort with which we ourselves are comforted by God."
    },
    {
      "id": "47.1.20",
      "ref": "2 Corinthians 1:20",
      "text": "For however many are the promises of God, in him is the “Yes.” Therefore also through him is the “Amen”, to the glory of God through us."
    },
    {
      "id": "47.3.17",
      "ref": "2 Corinthians 3:17",
      "text": "Now the Lord is the Spirit; and where the Spirit of the Lord is, there is liberty."
    },
    {
      "id": "47.4.16",
      "ref": "2 Corinthians 4:16",
      "text": "Therefore we don’t faint, but though our outward person is decaying, yet our inward person is renewed day by day."
    },
    {
      "id": "47.4.17-18",
      "ref": "2 Corinthians 4:17-18",
      "text": "For our light affliction, which is for the moment, works for us more and more exceedingly an eternal weight of glory, while we don’t look at the things which are seen, but at the things which are not seen. For the things which are seen are temporal, but the things which are not seen are eternal."
    },
    {
      "id": "47.5.7",
      "ref": "2 Corinthians 5:7",
      "text": "for we walk by faith, not by sight."
    },
    {
      "id": "47.5.17",
      "ref": "2 Corinthians 5:17",
      "text": "Therefore if anyone is in Christ, he is a new creation. The old things have passed away. Behold, all things have become new."
    },
    {
      "id": "47.9.7",
      "ref": "2 Corinthians 9:7",
      "text": "Let each man give according as he has determined in his heart, not grudgingly or under compulsion, for God loves a cheerful giver."
    },
    {
      "id": "47.9.8",
      "ref": "2 Corinthians 9:8",
      "text": "And God is able to make all grace abound to you, that you, always having all sufficiency in everything, may abound to every good work."
    },
    {
      "id": "47.10.5",
      "ref": "2 Corinthians 10:5",
      "text": "throwing down imaginations and every high thing that is exalted against the knowledge of God and bringing every thought into captivity to the obedience of Christ,"
    },
    {
      "id": "47.12.9",
      "ref": "2 Corinthians 12:9",
      "text": "He has said to me, “My grace is sufficient for you, for my power is made perfect in weakness.” Most gladly therefore I will rather glory in my weaknesses, that the power of Christ may rest on me."
    },
    {
      "id": "48.2.20",
      "ref": "Galatians 2:20",
      "text": "I have been crucified with Christ, and it is no longer I who live, but Christ lives in me. That life which I now live in the flesh, I live by faith in the Son of God, who loved me and gave himself up for me."
    },
    {
      "id": "48.3.26-28",
      "ref": "Galatians 3:26-28",
      "text": "For you are all children of God, through faith in Christ Jesus. For as many of you as were baptized into Christ have put on Christ. There is neither Jew nor Greek, there is neither slave nor free man, there is neither male nor female; for you are all one in Christ Jesus."
    },
    {
      "id": "48.5.1",
      "ref": "Galatians 5:1",
      "text": "Stand firm therefore in the liberty by which Christ has made us free, and don’t be entangled again with a yoke of bondage."
    },
    {
      "id": "48.5.13",
      "ref": "Galatians 5:13",
      "text": "For you, brothers, were called for freedom. Only don’t use your freedom as an opportunity for the flesh, but through love be servants to one another."
    },
    {
      "id": "48.5.22-23",
      "ref": "Galatians 5:22-23",
      "text": "But the fruit of the Spirit is love, joy, peace, patience, kindness, goodness, faith, gentleness, and self-control. Against such things there is no law."
    },
    {
      "id": "48.6.2",
      "ref": "Galatians 6:2",
      "text": "Bear one another’s burdens, and so fulfill the law of Christ."
    },
    {
      "id": "48.6.7",
      "ref": "Galatians 6:7",
      "text": "Don’t be deceived. God is not mocked, for whatever a man sows, that he will also reap."
    },
    {
      "id": "48.6.9",
      "ref": "Galatians 6:9",
      "text": "Let’s not be weary in doing good, for we will reap in due season if we don’t give up."
    },
    {
      "id": "49.1.3",
      "ref": "Ephesians 1:3",
      "text": "Blessed be the God and Father of our Lord Jesus Christ, who has blessed us with every spiritual blessing in the heavenly places in Christ,"
    },
    {
      "id": "49.2.8-9",
      "ref": "Ephesians 2:8-9",
      "text": "for by grace you have been saved through faith, and that not of yourselves; it is the gift of God, not of works, that no one would boast."
    },
    {
      "id": "49.2.10",
      "ref": "Ephesians 2:10",
      "text": "For we are his workmanship, created in Christ Jesus for good works, which God prepared before that we would walk in them."
    },
    {
      "id": "49.3.16-17",
      "ref": "Ephesians 3:16-17",
      "text": "that he would grant you, according to the riches of his glory, that you may be strengthened with power through his Spirit in the inner person, that Christ may dwell in your hearts through faith, to the end that you, being rooted and grounded in love,"
    },
    {
      "id": "49.3.20",
      "ref": "Ephesians 3:20",
      "text": "Now to him who is able to do exceedingly abundantly above all that we ask or think, according to the power that works in us,"
    },
    {
      "id": "49.4.2-3",
      "ref": "Ephesians 4:2-3",
      "text": "with all lowliness and humility, with patience, bearing with one another in love, being eager to keep the unity of the Spirit in the bond of peace."
    },
    {
      "id": "49.4.29",
      "ref": "Ephesians 4:29",
      "text": "Let no corrupt speech proceed out of your mouth, but only what is good for building others up as the need may be, that it may give grace to those who hear."
    },
    {
      "id": "49.4.32",
      "ref": "Ephesians 4:32",
      "text": "And be kind to one another, tender hearted, forgiving each other, just as God also in Christ forgave you."
    },
    {
      "id": "49.5.1-2",
      "ref": "Ephesians 5:1-2",
      "text": "Be therefore imitators of God, as beloved children. Walk in love, even as Christ also loved us and gave himself up for us, an offering and a sacrifice to God for a sweet-smelling fragrance."
    },
    {
      "id": "49.5.20",
      "ref": "Ephesians 5:20",
      "text": "giving thanks always concerning all things in the name of our Lord Jesus Christ to God, even the Father;"
    },
    {
      "id": "49.6.10",
      "ref": "Ephesians 6:10",
      "text": "Finally, be strong in the Lord and in the strength of his might."
    },
    {
      "id": "49.6.11",
      "ref": "Ephesians 6:11",
      "text": "Put on the whole armor of God, that you may be able to stand against the wiles of the devil."
    },
    {
      "id": "50.1.6",
      "ref": "Philippians 1:6",
      "text": "being confident of this very thing, that he who began a good work in you will complete it until the day of Jesus Christ."
    },
    {
      "id": "50.1.21",
      "ref": "Philippians 1:21",
      "text": "For to me to live is Christ, and to die is gain."
    },
    {
      "id": "50.2.3-4",
      "ref": "Philippians 2:3-4",
      "text": "doing nothing through rivalry or through conceit, but in humility, each counting others better than himself; each of you not just looking to his own things, but each of you also to the things of others."
    },
    {
      "id": "50.2.13",
      "ref": "Philippians 2:13",
      "text": "For it is God who works in you both to will and to work for his good pleasure."
    },
    {
      "id": "50.3.13-14",
      "ref": "Philippians 3:13-14",
      "text": "Brothers, I don’t regard myself as yet having taken hold, but one thing I do: forgetting the things which are behind and stretching forward to the things which are before, I press on toward the goal for the prize of the high calling of God in Christ Jesus."
    },
    {
      "id": "50.4.4",
      "ref": "Philippians 4:4",
      "text": "Rejoice in the Lord always! Again I will say, “Rejoice!”"
    },
    {
      "id": "50.4.6-7",
      "ref": "Philippians 4:6-7",
      "text": "In nothing be anxious, but in everything, by prayer and petition with thanksgiving, let your requests be made known to God. And the peace of God, which surpasses all understanding, will guard your hearts and your thoughts in Christ Jesus."
    },
    {
      "id": "50.4.8",
      "ref": "Philippians 4:8",
      "text": "Finally, brothers, whatever things are true, whatever things are honorable, whatever things are just, whatever things are pure, whatever things are lovely, whatever things are of good report: if there is any virtue and if there is anything worthy of praise, think about these things."
    },
    {
      "id": "50.4.13",
      "ref": "Philippians 4:13",
      "text": "I can do all things through Christ who strengthens me."
    },
    {
      "id": "50.4.19",
      "ref": "Philippians 4:19",
      "text": "My God will supply every need of yours according to his riches in glory in Christ Jesus."
    },
    {
      "id": "51.1.16-17",
      "ref": "Colossians 1:16-17",
      "text": "For by him all things were created in the heavens and on the earth, visible things and invisible things, whether thrones or dominions or principalities or powers. All things have been created through him and for him. He is before all things, and in him all things are held together."
    },
    {
      "id": "51.2.6-7",
      "ref": "Colossians 2:6-7",
      "text": "As therefore you received Christ Jesus the Lord, walk in him, rooted and built up in him and established in the faith, even as you were taught, abounding in it in thanksgiving."
    },
    {
      "id": "51.3.2",
      "ref": "Colossians 3:2",
      "text": "Set your mind on the things that are above, not on the things that are on the earth."
    },
    {
      "id": "51.3.12",
      "ref": "Colossians 3:12",
      "text": "Put on therefore, as God’s chosen ones, holy and beloved, a heart of compassion, kindness, lowliness, humility, and perseverance;"
    },
    {
      "id": "51.3.13",
      "ref": "Colossians 3:13",
      "text": "bearing with one another, and forgiving each other, if any man has a complaint against any; even as Christ forgave you, so you also do."
    },
    {
      "id": "51.3.15",
      "ref": "Colossians 3:15",
      "text": "And let the peace of God rule in your hearts, to which also you were called in one body, and be thankful."
    },
    {
      "id": "51.3.17",
      "ref": "Colossians 3:17",
      "text": "Whatever you do, in word or in deed, do all in the name of the Lord Jesus, giving thanks to God the Father through him."
    },
    {
      "id": "51.3.23",
      "ref": "Colossians 3:23",
      "text": "And whatever you do, work heartily, as for the Lord and not for men,"
    },
    {
      "id": "52.4.16-17",
      "ref": "1 Thessalonians 4:16-17",
      "text": "For the Lord himself will descend from heaven with a shout, with the voice of the archangel and with God’s trumpet. The dead in Christ will rise first, then we who are alive, who are left, will be caught up together with them in the clouds to meet the Lord in the air. So we will be with the Lord forever."
    },
    {
      "id": "52.5.11",
      "ref": "1 Thessalonians 5:11",
      "text": "Therefore exhort one another, and build each other up, even as you also do."
    },
    {
      "id": "52.5.16-18",
      "ref": "1 Thessalonians 5:16-18",
      "text": "Always rejoice. Pray without ceasing. In everything give thanks, for this is the will of God in Christ Jesus toward you."
    },
    {
      "id": "52.5.21",
      "ref": "1 Thessalonians 5:21",
      "text": "Test all things, and hold firmly that which is good."
    },
    {
      "id": "52.5.24",
      "ref": "1 Thessalonians 5:24",
      "text": "He who calls you is faithful, who will also do it."
    },
    {
      "id": "53.3.3",
      "ref": "2 Thessalonians 3:3",
      "text": "But the Lord is faithful, who will establish you and guard you from the evil one."
    },
    {
      "id": "53.3.16",
      "ref": "2 Thessalonians 3:16",
      "text": "Now may the Lord of peace himself give you peace at all times in all ways. The Lord be with you all."
    },
    {
      "id": "54.2.5",
      "ref": "1 Timothy 2:5",
      "text": "For there is one God and one mediator between God and men, the man Christ Jesus,"
    },
    {
      "id": "54.4.12",
      "ref": "1 Timothy 4:12",
      "text": "Let no man despise your youth; but be an example to those who believe, in word, in your way of life, in love, in spirit, in faith, and in purity."
    },
    {
      "id": "54.6.6-7",
      "ref": "1 Timothy 6:6-7",
      "text": "But godliness with contentment is great gain. For we brought nothing into the world, and we certainly can’t carry anything out."
    },
    {
      "id": "54.6.12",
      "ref": "1 Timothy 6:12",
      "text": "Fight the good fight of faith. Take hold of the eternal life to which you were called, and you confessed the good confession in the sight of many witnesses."
    },
    {
      "id": "55.1.7",
      "ref": "2 Timothy 1:7",
      "text": "For God didn’t give us a spirit of fear, but of power, love, and self-control."
    },
    {
      "id": "55.1.9",
      "ref": "2 Timothy 1:9",
      "text": "who saved us and called us with a holy calling, not according to our works, but according to his own purpose and grace, which was given to us in Christ Jesus before times eternal,"
    },
    {
      "id": "55.2.15",
      "ref": "2 Timothy 2:15",
      "text": "Give diligence to present yourself approved by God, a workman who doesn’t need to be ashamed, properly handling the Word of Truth."
    },
    {
      "id": "55.3.16-17",
      "ref": "2 Timothy 3:16-17",
      "text": "Every Scripture is God-breathed and profitable for teaching, for reproof, for correction, and for instruction in righteousness, that each person who belongs to God may be complete, thoroughly equipped for every good work."
    },
    {
      "id": "55.4.7",
      "ref": "2 Timothy 4:7",
      "text": "I have fought the good fight. I have finished the course. I have kept the faith."
    },
    {
      "id": "56.2.11-12",
      "ref": "Titus 2:11-12",
      "text": "For the grace of God has appeared, bringing salvation to all men, instructing us to the intent that, denying ungodliness and worldly lusts, we would live soberly, righteously, and godly in this present age;"
    },
    {
      "id": "56.3.5",
      "ref": "Titus 3:5",
      "text": "not by works of righteousness which we did ourselves, but according to his mercy, he saved us through the washing of regeneration and renewing by the Holy Spirit,"
    },
    {
      "id": "58.4.12",
      "ref": "Hebrews 4:12",
      "text": "For the word of God is living and active, and sharper than any two-edged sword, piercing even to the dividing of soul and spirit, of both joints and marrow, and is able to discern the thoughts and intentions of the heart."
    },
    {
      "id": "58.4.16",
      "ref": "Hebrews 4:16",
      "text": "Let’s therefore draw near with boldness to the throne of grace, that we may receive mercy and may find grace for help in time of need."
    },
    {
      "id": "58.6.19",
      "ref": "Hebrews 6:19",
      "text": "This hope we have as an anchor of the soul, a hope both sure and steadfast and entering into that which is within the veil,"
    },
    {
      "id": "58.10.23",
      "ref": "Hebrews 10:23",
      "text": "let’s hold fast the confession of our hope without wavering; for he who promised is faithful."
    },
    {
      "id": "58.10.24-25",
      "ref": "Hebrews 10:24-25",
      "text": "Let’s consider how to provoke one another to love and good works, not forsaking our own assembling together, as the custom of some is, but exhorting one another, and so much the more as you see the Day approaching."
    },
    {
      "id": "58.11.1",
      "ref": "Hebrews 11:1",
      "text": "Now faith is assurance of things hoped for, proof of things not seen."
    },
    {
      "id": "58.11.6",
      "ref": "Hebrews 11:6",
      "text": "Without faith it is impossible to be well pleasing to him, for he who comes to God must believe that he exists, and that he is a rewarder of those who seek him."
    },
    {
      "id": "58.12.1-2",
      "ref": "Hebrews 12:1-2",
      "text": "Therefore let’s also, seeing we are surrounded by so great a cloud of witnesses, lay aside every weight and the sin which so easily entangles us, and let’s run with perseverance the race that is set before us, looking to Jesus, the author and perfecter of faith, who for the joy that was set before him endured the cross, despising its shame, and has sat down at the right hand of the throne of God."
    },
    {
      "id": "58.12.11",
      "ref": "Hebrews 12:11",
      "text": "All chastening seems for the present to be not joyous but grievous; yet afterward it yields the peaceful fruit of righteousness to those who have been trained by it."
    },
    {
      "id": "58.13.5",
      "ref": "Hebrews 13:5",
      "text": "Be free from the love of money, content with such things as you have, for he has said, “I will in no way leave you, neither will I in any way forsake you.”"
    },
    {
      "id": "58.13.6",
      "ref": "Hebrews 13:6",
      "text": "So that with good courage we say, “The Lord is my helper. I will not fear. What can man do to me?”"
    },
    {
      "id": "58.13.8",
      "ref": "Hebrews 13:8",
      "text": "Jesus Christ is the same yesterday, today, and forever."
    },
    {
      "id": "59.1.2-3",
      "ref": "James 1:2-3",
      "text": "Count it all joy, my brothers, when you fall into various temptations, knowing that the testing of your faith produces endurance."
    },
    {
      "id": "59.1.5",
      "ref": "James 1:5",
      "text": "But if any of you lacks wisdom, let him ask of God, who gives to all liberally and without reproach, and it will be given to him."
    },
    {
      "id": "59.1.12",
      "ref": "James 1:12",
      "text": "Blessed is a person who endures temptation, for when he has been approved, he will receive the crown of life which the Lord promised to those who love him."
    },
    {
      "id": "59.1.17",
      "ref": "James 1:17",
      "text": "Every good gift and every perfect gift is from above, coming down from the Father of lights, with whom can be no variation nor turning shadow."
    },
    {
      "id": "59.1.19",
      "ref": "James 1:19",
      "text": "So, then, my beloved brothers, let every man be swift to hear, slow to speak, and slow to anger;"
    },
    {
      "id": "59.1.22",
      "ref": "James 1:22",
      "text": "But be doers of the word, and not only hearers, deluding your own selves."
    },
    {
      "id": "59.4.7",
      "ref": "James 4:7",
      "text": "Be subject therefore to God. Resist the devil, and he will flee from you."
    },
    {
      "id": "59.4.8",
      "ref": "James 4:8",
      "text": "Draw near to God, and he will draw near to you. Cleanse your hands, you sinners. Purify your hearts, you double-minded."
    },
    {
      "id": "59.5.16",
      "ref": "James 5:16",
      "text": "Confess your sins to one another and pray for one another, that you may be healed. The insistent prayer of a righteous person is powerfully effective."
    },
    {
      "id": "60.1.3",
      "ref": "1 Peter 1:3",
      "text": "Blessed be the God and Father of our Lord Jesus Christ, who according to his great mercy caused us to be born again to a living hope through the resurrection of Jesus Christ from the dead,"
    },
    {
      "id": "60.1.6-7",
      "ref": "1 Peter 1:6-7",
      "text": "In this you greatly rejoice, though now for a little while, if need be, you have been grieved in various trials, that the proof of your faith, which is more precious than gold that perishes, even though it is tested by fire, may be found to result in praise, glory, and honor at the revelation of Jesus Christ—"
    },
    {
      "id": "60.2.9",
      "ref": "1 Peter 2:9",
      "text": "But you are a chosen race, a royal priesthood, a holy nation, a people for God’s own possession, that you may proclaim the excellence of him who called you out of darkness into his marvelous light."
    },
    {
      "id": "60.2.24",
      "ref": "1 Peter 2:24",
      "text": "He himself bore our sins in his body on the tree, that we, having died to sins, might live to righteousness. You were healed by his wounds."
    },
    {
      "id": "60.3.15",
      "ref": "1 Peter 3:15",
      "text": "But sanctify the Lord God in your hearts. Always be ready to give an answer to everyone who asks you a reason concerning the hope that is in you, with humility and fear,"
    },
    {
      "id": "60.4.8",
      "ref": "1 Peter 4:8",
      "text": "And above all things be earnest in your love among yourselves, for love covers a multitude of sins."
    },
    {
      "id": "60.4.10",
      "ref": "1 Peter 4:10",
      "text": "As each has received a gift, employ it in serving one another, as good managers of the grace of God in its various forms."
    },
    {
      "id": "60.5.6-7",
      "ref": "1 Peter 5:6-7",
      "text": "Humble yourselves therefore under the mighty hand of God, that he may exalt you in due time, casting all your worries on him, because he cares for you."
    },
    {
      "id": "60.5.8",
      "ref": "1 Peter 5:8",
      "text": "Be sober and self-controlled. Be watchful. Your adversary, the devil, walks around like a roaring lion, seeking whom he may devour."
    },
    {
      "id": "60.5.10",
      "ref": "1 Peter 5:10",
      "text": "But may the God of all grace, who called you to his eternal glory by Christ Jesus, after you have suffered a little while, perfect, establish, strengthen, and settle you."
    },
    {
      "id": "61.1.3",
      "ref": "2 Peter 1:3",
      "text": "seeing that his divine power has granted to us all things that pertain to life and godliness, through the knowledge of him who called us by his own glory and virtue,"
    },
    {
      "id": "61.3.9",
      "ref": "2 Peter 3:9",
      "text": "The Lord is not slow concerning his promise, as some count slowness; but he is patient with us, not wishing that anyone should perish, but that all should come to repentance."
    },
    {
      "id": "61.3.18",
      "ref": "2 Peter 3:18",
      "text": "But grow in the grace and knowledge of our Lord and Savior Jesus Christ. To him be the glory both now and forever. Amen."
    },
    {
      "id": "62.1.9",
      "ref": "1 John 1:9",
      "text": "If we confess our sins, he is faithful and righteous to forgive us the sins and to cleanse us from all unrighteousness."
    },
    {
      "id": "62.3.1",
      "ref": "1 John 3:1",
      "text": "See how great a love the Father has given to us, that we should be called children of God! For this cause the world doesn’t know us, because it didn’t know him."
    },
    {
      "id": "62.3.16",
      "ref": "1 John 3:16",
      "text": "By this we know love, because he laid down his life for us. And we ought to lay down our lives for the brothers."
    },
    {
      "id": "62.3.18",
      "ref": "1 John 3:18",
      "text": "My little children, let’s not love in word only, or with the tongue only, but in deed and truth."
    },
    {
      "id": "62.4.7",
      "ref": "1 John 4:7",
      "text": "Beloved, let’s love one another, for love is of God; and everyone who loves has been born of God and knows God."
    },
    {
      "id": "62.4.9-10",
      "ref": "1 John 4:9-10",
      "text": "By this God’s love was revealed in us, that God has sent his only born Son into the world that we might live through him. In this is love, not that we loved God, but that he loved us, and sent his Son as the atoning sacrifice for our sins."
    },
    {
      "id": "62.4.16",
      "ref": "1 John 4:16",
      "text": "We know and have believed the love which God has for us. God is love, and he who remains in love remains in God, and God remains in him."
    },
    {
      "id": "62.4.18",
      "ref": "1 John 4:18",
      "text": "There is no fear in love; but perfect love casts out fear, because fear has punishment. He who fears is not made perfect in love."
    },
    {
      "id": "62.4.19",
      "ref": "1 John 4:19",
      "text": "We love him, because he first loved us."
    },
    {
      "id": "62.5.14",
      "ref": "1 John 5:14",
      "text": "This is the boldness which we have toward him, that if we ask anything according to his will, he listens to us."
    },
    {
      "id": "65.1.24-25",
      "ref": "Jude 1:24-25",
      "text": "Now to him who is able to keep them from stumbling, and to present you faultless before the presence of his glory in great joy, to God our Savior, who alone is wise, be glory and majesty, dominion and power, both now and forever. Amen."
    },
    {
      "id": "66.1.8",
      "ref": "Revelation 1:8",
      "text": "“I am the Alpha and the Omega,” says the Lord God, “who is and who was and who is to come, the Almighty.”"
    },
    {
      "id": "66.2.10",
      "ref": "Revelation 2:10",
      "text": "Don’t be afraid of the things which you are about to suffer. Behold, the devil is about to throw some of you into prison, that you may be tested; and you will have oppression for ten days. Be faithful to death, and I will give you the crown of life."
    },
    {
      "id": "66.3.20",
      "ref": "Revelation 3:20",
      "text": "Behold, I stand at the door and knock. If anyone hears my voice and opens the door, then I will come in to him and will dine with him, and he with me."
    },
    {
      "id": "66.7.17",
      "ref": "Revelation 7:17",
      "text": "for the Lamb who is in the middle of the throne shepherds them and leads them to springs of life-giving waters. And God will wipe away every tear from their eyes.”"
    },
    {
      "id": "66.21.3-4",
      "ref": "Revelation 21:3-4",
      "text": "I heard a loud voice out of heaven saying, “Behold, God’s dwelling is with people; and he will dwell with them, and they will be his people, and God himself will be with them as their God. He will wipe away every tear from their eyes. Death will be no more; neither will there be mourning, nor crying, nor pain any more. The first things have passed away.”"
    },
    {
      "id": "66.21.5",
      "ref": "Revelation 21:5",
      "text": "He who sits on the throne said, “Behold, I am making all things new.” He said, “Write, for these words of God are faithful and true.”"
    },
    {
      "id": "66.22.13",
      "ref": "Revelation 22:13",
      "text": "I am the Alpha and the Omega, the First and the Last, the Beginning and the End."
    }
  ]
};
