#!/usr/bin/env python3
"""Copy the shared assets into both frontends.

The KDE Store and cinnamon-spices distribute self-contained packages, so each
frontend carries its own copy of shared/selection.js and the verse data. These
copies are generated — edit the originals, then run this script.

The desklet reads the JSON files directly through Gio. The plasmoid cannot: Qt 6
refuses XMLHttpRequest on local files, so the same data is emitted as QML
JavaScript library modules that main.qml imports statically.

Usage:
    python3 tools/sync_assets.py            # copy
    python3 tools/sync_assets.py --check    # fail if a copy is stale
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DESKLET_UUID = "bible-verse@technikweber"

TARGETS = [
    ROOT / "plasmoid" / "package" / "contents",
    ROOT / "desklet" / DESKLET_UUID,
]


PLASMOID_UI = ROOT / "plasmoid" / "package" / "contents" / "ui"
DESKLET_DIR = ROOT / "desklet" / DESKLET_UUID


def verse_files() -> list[Path]:
    return sorted((ROOT / "data" / "verses").glob("*.json"))


def qml_module(source: Path) -> str:
    """Wrap a verse file as a QML JavaScript library module."""
    data = json.loads(source.read_text("utf-8"))
    return (
        "/* Generated by tools/sync_assets.py — do not edit.\n"
        f" * Source: data/verses/{source.name}\n"
        " */\n"
        ".pragma library\n\n"
        "var DATA = " + json.dumps(data, ensure_ascii=False, indent=2) + ";\n"
    )


def contents() -> list[tuple[Path, bytes]]:
    """Every generated file and the bytes it must contain."""
    selection = (ROOT / "shared" / "selection.js").read_bytes()
    result = [
        (PLASMOID_UI / "selection.js", selection),
        (DESKLET_DIR / "selection.js", selection),
    ]
    for source in verse_files():
        lang = source.stem
        result.append((DESKLET_DIR / "data" / source.name, source.read_bytes()))
        result.append((PLASMOID_UI / ("verses_" + lang + ".js"),
                       qml_module(source).encode("utf-8")))
    return result


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    stale = []
    for target, payload in contents():
        current = target.read_bytes() if target.exists() else None
        if current == payload:
            continue
        if args.check:
            stale.append(str(target.relative_to(ROOT)))
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(payload)
            print(f"  {target.relative_to(ROOT)}", file=sys.stderr)

    if stale:
        raise SystemExit("stale, re-run tools/sync_assets.py: " + ", ".join(stale))
    print("OK", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
